language: php
before_script:
 # Setup Coveralls and httpbin-php
 - phpenv local 5.5
 - composer install --dev --no-interaction
 - TESTPHPBIN=$(phpenv which php)
 - sudo PHPBIN=$TESTPHPBIN vendor/bin/start.sh
 - export REQUESTS_TEST_HOST_HTTP=localhost
 - phpenv local --unset

 # Work out of the tests directory
script:
 - phpunit --coverage-clover clover.xml
after_script:
 - cd ..
 - phpenv local 5.5
 - sudo PATH=$PATH vendor/bin/stop.sh
 - php vendor/bin/coveralls -v
 - phpenv local --unset
 
php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6


matrix:
  allow_failures:
    - php: 5.3
