language: php
before_script:
 # Setup Coveralls 
 - composer install --dev --no-interaction 
script:
 - phpunit --coverage-clover clover.xml
after_script:
 - php vendor/bin/coveralls -v
php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    
matrix:
  allow_failures:
    - php: 5.3
